#ifndef VIDEOUDPSHARED_H
#define VIDEOUDPSHARED_H

#include <netinet/in.h>
#include <stdbool.h>

#define HEADER_UTIMESTAMP_SIZE ((ssize_t)(sizeof(uint64_t)))
#define HEADER_PACKET_INDEX_SIZE ((ssize_t)(sizeof(uint32_t)))
#define HEADER_PACKET_COUNT_SIZE ((ssize_t)(sizeof(uint32_t)))
#define HEADER_BODY_LENGTH_SIZE ((ssize_t)(sizeof(uint32_t)))
#define HEADER_LENGTH (HEADER_UTIMESTAMP_SIZE + HEADER_PACKET_INDEX_SIZE + HEADER_PACKET_COUNT_SIZE + HEADER_BODY_LENGTH_SIZE)
#define HEADER_UTIMESTAMP_OFFSET ((ssize_t)(0))
#define HEADER_PACKET_INDEX_OFFSET (HEADER_UTIMESTAMP_SIZE)
#define HEADER_PACKET_COUNT_OFFSET (HEADER_PACKET_INDEX_OFFSET + HEADER_PACKET_INDEX_SIZE)
#define HEADER_BODY_LENGTH_OFFSET (HEADER_PACKET_COUNT_OFFSET + HEADER_PACKET_COUNT_SIZE)
#define PACKET_BODY_START_OFFSET (HEADER_BODY_LENGTH_OFFSET + HEADER_BODY_LENGTH_SIZE)

int VideoUDPSharedCreateSocket(struct sockaddr_in* localAddress);

#endif